---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gleamfan.
--- DateTime: 2021/5/12 上午10:49
---

--安装redis驱动 luarocks install redis-lua
--测试redis
local redis = require 'redis'
client = redis.connect('127.0.0.1', 55000)
local response = client:ping()
--for i=1,10 do
--    client:set("post_"..i,"a"..i)
--end
--编写redis.call
redis.call = function(cmd, ...)
    return assert(load('return client:'.. string.lower(cmd) ..'(...)'))(...)
end

--在lua里面切换redis的DB
--redis.call('select',0)
--使用redis.call调用

--hash
local flag = redis.call("hexists","tracy3","3")
print("flag:",flag,tonumber(flag))
if(flag) then
    print('exist')
else
    redis.call("hmset","tracy3","3","333333")
    print("not exist")
end

local value = redis.call("hget","tracy2",3)
print("value:",value)
--local valueTable = redis.call("hmget","tracy2",2,3)
--print(table.concat(valueTable,","))
local valueTable = redis.call("hgetall","tracy6")
for key, value in pairs(valueTable) do
    print(key.."--"..value)
end
local result = redis.call("get","tracy5")
print(result)
local result1 = client:hgetall("tracy6")
for key, value in pairs(result1) do
    print(key.."--"..value)
end
for index, value in ipairs(result1) do
    print(index.."--"..value)
end
local result2 = client:hset("tracy6",6,6)
print(result2)

local hlen = redis.call("hlen","tracy2")
print("length:"..hlen)

--list队列
--local listRes = redis.call("lpush","list",123)
--print(listRes)
local popMem = redis.call("rpop","list")
print(popMem)
--kv with ttl
local kvRes = redis.call("set","tracy7",7,"NX","EX",30)
print(kvRes)

--zset
local flag = redis.call("zadd","zset",3,"wangwu")
print(flag)
local flag = redis.call("zincrby","zset",1,"wangwu")
print(flag)
local score = redis.call("zscore","zset","wangwu")
print("zset score:",score)
--withoutscores
-- local result = redis.call("zrevrangebyscore","zset",4,2,"limit",0,2)
--WITHSCORES
local result = redis.call("zrevrangebyscore","zset",4,2,"WITHSCORES","limit",0,2)
for k, v in pairs(result) do
    print(k..":")
    for j,v2 in pairs(v) do
        print(j.."--"..v2)
    end
end

local flag = redis.call("zrem","zset","lisi")
print("zrem flag:",flag)
local flag = redis.call("del","tracy3")
print("del flag:",flag)
local result = redis.call("expire","tracy2",30)
print("expire result:",result)



